### ISSUE TITLE
Cannot read property 'indexOf' of undefined]

### ISSUE THREAD

**Issue by viyirenov** [remvst/js13k-compiler#2]
@remvst 
I'm using windows and when I try the command: `node ..\js13k-compiler\bin\build config.json`, i'm getting this error:

```
Mangling names...
[TypeError: Cannot read property 'indexOf' of undefined]
```

**Comment by viyirenov** [comment]
I just noticed you updated your code. Just don't forget to create a build folder before building or you will get an error saying that the game.html file or folder doesn't exist.

**Comment by remvst** [comment]
@viyirenov yeah currently the folders aren't created automatically. I need to look into doing that, but since I'm pretty much the only person to use the compiler, I didn't think it was worth the time.

**Comment by viyirenov** [comment]
@remvst That is awesome. Keep doing the good work.
